twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        ['bootstrap_5_layout.html.twig']
    globals:
        posters_dir: '%app.posters.dir%'

when@test:
    twig:
        strict_variables: true
